package Orders.enums;

public enum ItemStatus {
    PREPARING,
    READY,
    SERVED,
    CANCELLED

    //NO NEED FOR PENDING AND CONFIRMED HERE AS PEOPLE
    //USUALLY BUY THE WHOLE ORDER NOT INDIVIDUAL ITEMS
}
